### ISSUE TITLE
[RFE] dev.ci Dockerize the install to avoid changing the local environment

### ISSUE THREAD

**Issue by blaisep** [PyBites-Open-Source/karmabot#101]
(I can take this one.)
@bbelderbos , I suggest group of files which will allow a contributor to build and run a local instance without making any changes to their local set up. It would look a bit like the [docker-compose](https://github.com/blaisep-vgs/fastpi_tdd_docker/blob/master/docker-compose.yaml) and the [Dockerfile](https://github.com/blaisep-vgs/fastpi_tdd_docker/blob/master/project/Dockerfile) that I used in a tutorial.

**Comment by bbelderbos** [comment]
Thanks @blaisep I like that, last year somebody did this for PyBites Books (https://github.com/PyBites-Open-Source/pbreadinglist) which I tried last week and was very convenient.

**Comment by pogross** [comment]
Still relevant? Otherwise I will close this :)

**Comment by bbelderbos** [comment]
@blaisep closing for now, we can re-open if you still want to do it. In that case please submit a PR. Thanks.
