### ISSUE TITLE
rtm.start behavior changing

### ISSUE THREAD

**Issue by gustavogattino** [PyBites-Open-Source/karmabot#102]
Hello there!

I just received the following email from Slack:

> As a contributor or owner of Karmabot that recently used the rtm.start Web API method, we wanted to inform you about two important changes coming to rtm.start:
> 	
> November 30, 2021
> New Slack apps and integrations will no longer be able to use rtm.start and must use rtm.connect instead.
>  
> September 20, 2022
> The response from rtm.start will transform into the brief response found in the method that replaces it, rtm.connect.

I went through the bot's code but couldn't find where it is using the rtm.start method. Is there anything I should do to prevent the bot from breaking when they make the changes?

Thanks!

Cheers,
Gustavo

**Comment by pogross** [comment]
I think that was solved as we updated to a newer version of the Slack package. Thanks for the hint.
