### ISSUE TITLE
pre-commit.ci fails

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/karmabot#107]
https://results.pre-commit.ci/run/github/95367692/1675291955.UbCFoshYRhOE4yLglvCZRg

Issue search:
https://github.com/desktop/desktop/issues/15671#issuecomment-1325494211

https://github.com/PyBites-Open-Source/karmabot/blob/master/.pre-commit-config.yaml -> only flake8 == gitlab which if you go to the link you indeed need to login

First change I am trying is to update the link to GH -> https://github.com/pycqa/flake8

**Comment by bbelderbos** [comment]
Ran it again on PR but now hitting a different issue: https://results.pre-commit.ci/run/github/95367692/1675335341.2zxL6BzNRdOoNxR53NxHAQ

```
             RuntimeError: The Poetry configuration is invalid:
                - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```

**Comment by pogross** [comment]
fixed
