### ISSUE TITLE
Karmabot does undesirable karma changes

### ISSUE THREAD

**Issue by pogross** [PyBites-Open-Source/karmabot#21]
### Problem
Karmabot changes karma of users that do not exists or for "non-user" entities

### Example
```
Somebody 16:49 Uhr
print("--------")

karmabotAPP 16:49 Uhr
print("'s karma decreased to -5 (= max decrease of 5)
```

### Possible fix
Introduce checks, if user really exists and changes are "valid"

1. User exists check
2. Command syntax check -> there should be only one way/command format to do it

### Further implications
This may need some kind of alias list if user has multiple "identities" 
Karma-Giver should be informed if karma giving fails.

**Comment by pogross** [comment]
Should be fixed by #22

**Comment by pybites** [comment]
@pogross this should be fixed now because we only apply karma to valid user handles, no?

**Comment by pogross** [comment]
@pybites yes the giving karma to non-users is fixed. 

However, there is still room for improvement of the  handling. Currently, "wrong" karma changes drip down until https://github.com/PyBites-Open-Source/karmabot/blob/d6319115f45f99264801ea76d8ddac85b431380b/bot/karma.py#L55-L63 and then handled by the exception thrown because the non-user does not exist. Also, this creates unnecessary API cals.

With better pattern matching this could already be discarded at
https://github.com/PyBites-Open-Source/karmabot/blob/d6319115f45f99264801ea76d8ddac85b431380b/main.py#L23

**Comment by pogross** [comment]
Based on the new message parsing and the check against the DB with slack user ids there should be no more undesirable karma changes.
