### ISSUE TITLE
[Improvement] joke category selection

### ISSUE THREAD

**Issue by pogross** [PyBites-Open-Source/karmabot#37]
# Joke category selection
https://github.com/PyBites-Open-Source/karmabot/blob/ae3871c55db03252683797dbe1f0764ea53b9f1f/commands/joke.py#L17-L21

# Suggestion by @fuzzygwalchmei
use `choice = dict.get(user_text.lower(), "all")` as easier and adaptive approach

# Problem
User may misspell command and/or add additional words in text

# Fix
Check all words and find the most similar command.
Potential approaches:

- https://pypi.org/project/fuzzywuzzy/
- https://codechalleng.es/bites/185/

Further a `dict` of available commands needs to be derived from the PyJokes package.

**Comment by pmayd** [comment]
will look into this

**Comment by pogross** [comment]
Solved. Thanks @pmayd 👍
