### ISSUE TITLE
Update to latest slackclient API

### ISSUE THREAD

**Issue by pmayd** [PyBites-Open-Source/karmabot#53]
I had not the time to fully go through the changes that were done in the API and that are required in our code base, but I have the strong feeling that we should update our code to match the latest Slack API. 

That is especially important because we rely on legacy tokens `xoxp` and `xoxb` for the app to authenticate itself via the slack API. However, as far as I know, this is no longer recommended by Slack (hence legacy) and it is not easy to create a legacy app that generates these tokens for you. As far as I understand, the more modern approach is via client secrets and client credentials, that are displayed at the landing page of one's app in the Slack dev page.

**Comment by pogross** [comment]
Some commands are now deprecated so we have to do this soonish

**Comment by pogross** [comment]
Will be fixed by #82

**Comment by pogross** [comment]
Done 😎
