### ISSUE TITLE
Create/Update and CONTRIBUTING Guidelines

### ISSUE THREAD

**Issue by pogross** [PyBites-Open-Source/karmabot#55]
Overhaul the [Readme section](https://github.com/PyBites-Open-Source/karmabot#development-pattern-for-contributors) and move it to `CONTRIBUTING.md`. 

- [Github](https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)
- [Example](https://github.com/asottile/pytest/blob/master/CONTRIBUTING.rst)

**Comment by ramesht007** [comment]
hey, @pogross I would like to work on this

**Comment by pogross** [comment]
This will require you to trial a bit with the current poetry and nox description. The new `CONTRIBUTING.md` should present a clear way for setting up the environment. Maybe @pmayd can also add some suggestions as he experience some difficulties with it.

**Comment by ramesht007** [comment]
thank you @pogross

**Comment by pmayd** [comment]
Indeed I did a whole and very long contrib. MD in the old project no idea where this file is... It is indeed a lot of work to properly explain how to setup the development environment, how to work with poetry and nox, especially under windows and finally how to create your own slack app

**Comment by pogross** [comment]
Whoops, I think it got lost in the transition to hypermodern. [Here it is](https://github.com/PyBites-Open-Source/karmabot/commit/03e952ae20b943cca33baccd5222f4c815044fc2?short_path=9fc63fa#diff-9fc63fa48a612a29c19d6eb425058d99). Content is pretty much outdated but the structure may help.

**Comment by tdchua** [comment]
Hi! I would also like to try my hand on this. May I know if it is okay?

**Comment by abirbhattacharya82** [comment]
I have created a lot of Markdown files previously. I can work on it. If you assign it to me

**Comment by pmayd** [comment]
I don't see the need for assigning someone to this issue as there are several people interested in working on this. No need to ask for permission either, just create a PR with your work or changes. However, in this case, you should make sure that you incorporate the changes of the others if a PR is accepted before your own PR.

**Comment by pmayd** [comment]
@abirbhattacharya82 thanks for the file but this is not the issue here, we seek someone who updates the existing document with information about how to get started with the project and how to setup your own dev env for working with a slack bot

**Comment by abirbhattacharya82** [comment]
Since the issue was to Create a Contributing.md for Hacktoberfest specially I provided a markdown file which will be a guidlines for people willing to contribute for Hacktoberfest. Also I have menntioned steps for newbies on how to get started.

**Comment by pmayd** [comment]
That is nice but not what we asked

**Comment by pmayd** [comment]
Read the first post everything is there.

**Comment by abirbhattacharya82** [comment]
Yaa Yaa it was my bad... I didn't see it at first

**Comment by ramesht007** [comment]
Hey, @pogross do I have to add slack support also!!

**Comment by pogross** [comment]
I don't really get what  you are referring to. Can you explain a bit  more what you mean?

**Comment by ramesht007** [comment]
As in the above link which you shared, In that file slack support was shone. so that I was asking shouls I also that add the same.

**Comment by pogross** [comment]
If you think it is important to setup the dev environment its should be included. You should test your instructions and see if it allows you to properly setup a dev environment for the project.
