### ISSUE TITLE
Explanation of Karma concept in welcome message

### ISSUE THREAD

**Issue by pogross** [PyBites-Open-Source/karmabot#58]
# Problem

Users may not understand the concept of giving and receiving karma based on the implicit and very short example given by the welcome message. (originally #30)

# Solution

Enhance welcome message with clear explanation of karma giving/receiving. Ideal would be a more elaborate welcome message with some examples and instructions. The goal is that a non-technical person without any prior knowledge to slack can grasp the concept.

**Comment by Rahul30032** [comment]
Can you assign this to me if not yet assigned to anyone? I can add elaborate introduction on Karma explaining with a few examples. Do I make changes to the readme.md file then?

**Comment by MishManners** [comment]
I'd love to give this a crack as well!

**Comment by pogross** [comment]
Sure, go for it @MishManners 😃
