### ISSUE TITLE
Scheduled backup task of Karma DB

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/karmabot#8]

**Comment by c4talyst** [comment]
Idea:
- Adjust code to only write to `KARMA_CACHE` if karma has changed
- Side-car to watch modified time on `KARMA_CACHE`, upload to storage bucket (S3, GCS)
- Init script (in `run.sh`) to download `KARMA_CACHE` before launch

**Comment by pogross** [comment]
Fixed by #22. Now needs backing up of the database :)

**Comment by bbelderbos** [comment]
Still on the free postgres tier on Heroku, but will take a weekly backup manually for now :) - thanks

**Comment by bbelderbos** [comment]
We can also write a scheduler job to do it :)

**Comment by pogross** [comment]
Status? :) Still on free tier?

**Comment by pogross** [comment]
@bbelderbos ping

**Comment by bbelderbos** [comment]
Thanks @pogross let's upgrade the DB to get this done daily automatically, seems we inevitably are also going to hit the 10k row limit of the free DB tier:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/387927/93988751-62505480-fd89-11ea-98ce-8bcf4ebe8c50.png">

**Comment by pogross** [comment]
status? @bbelderbos

**Comment by bbelderbos** [comment]
@pogross yes this is in place since we upgrade the DB tier, thanks for checking.
