### ISSUE TITLE
Make KARMABOT_TEST_MODE optional

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/karmabot#84]
I had to set it in UAT (and now PROD), would be nice to default it to `False` if not set.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/387927/126969938-91de54b8-96c0-4791-a7af-bc13a2cba9fb.png">

**Comment by pogross** [comment]
#97 Done. Thx @bbelderbos
