### ISSUE TITLE
Spotted 2 key errors in logs

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/karmabot#88]
Just FYI:

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/387927/127731489-49fc3bd6-21da-4643-a3b5-ebc6ab4d80ee.png">

And:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/387927/127731514-6266c475-db39-4e23-a907-8b23f8332a26.png">

This one happened right after new user creation + karma change (anonymised):

```
Jul 30 22:09:07 pbkarmabot app/worker.1 07-31 05:09 root         INFO     Created new KarmaUser: <KarmaUser> ID: yyy | Username: yyy | Karma-Points: 0
Jul 30 22:09:07 pbkarmabot app/worker.1 07-31 05:09 root         INFO     [Karmachange] aaa to bbb: 2
```

Let me know if I can help in any way ...

Thanks,
Bob

**Comment by pogross** [comment]
Was that in a private channel? Maybe you are still missing some permissions on the bot (group permissions). 

Otherwise, we need to reproduce it and look into the slack API response. However, we should at some try excepts around API calls and `logging.error` the API responses.

**Comment by bbelderbos** [comment]
Yep the permissions fixed the private channel issue but I think these errors are unrelated. Thanks for adding logging around this issue in your latest PR.

**Comment by bbelderbos** [comment]
@pogross thanks for the logging, that is useful.

I saw it happening just now again for this message you sent in the public karmabot dev channel: "and for master there was still the old 3.7 test, even if they were removed in the yml. I updated the workflows (edited)" - could it be related to the fact you edited this message?

It seems in that case the payload changes to (from Papertrail):

```
{'channel': 'C7R9H8B0S',
 'channel_type': 'channel',
 'event_ts': '1631102455.012700',
 'hidden': True,
 'message': { ... "text": ..., "user": ...}. => these are now one level deeper
...}
```

But when I try to reproduce it locally I get all attributes on the first level (as it's supposed to be):

```
{...'type': 'message', 'text': 'and for master there was still the old 3.7 test, even if they were removed in the yml. I updated the workflows', 'user': '...', ..., 'channel': 'C02DH32JCF4', ... 'channel_type': 'channel'}
```

So not sure yet how to fix this because I don't know why the response dict changes ...

**Comment by pogross** [comment]
@bbelderbos still happening or can we close this?

**Comment by bbelderbos** [comment]
Let's close for now, bot seems to work as expected.
