### ISSUE TITLE
Push 1.4 to pypi

### ISSUE THREAD

**Issue by c4talyst** [PyBites-Open-Source/karmabot#94]
https://pypi.org/project/karmabot/ has v1.3 when v1.4 is live

**Comment by bbelderbos** [comment]
Thanks @c4talyst I get it updated. @pogross we should automate this :) - GH Actions?

**Comment by bbelderbos** [comment]
Finally, we should have this soon :) 
https://github.com/PyBites-Open-Source/karmabot/pull/99
Sorry for the delay.
