### ISSUE TITLE
Manage environment variables purely by 3rd party library?

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/karmabot#98]
Btw why do we have this function? I would expect python-dotenv, python-decouple can do all this?

_Originally posted by @bbelderbos in https://github.com/PyBites-Open-Source/karmabot/pull/97#discussion_r704301640_

**Comment by pogross** [comment]
See #43 I think.

**Comment by bbelderbos** [comment]
ok thanks, let's leave it as is then for now.
